# Generated by Django 5.2.7 on 2025-10-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_created_at_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
